sudo: true
language: node_js
node_js:
  - "8"

branches:
  only:
    - /.*/

install:
  - /usr/bin/yarn install --production=false
  # - npm run test

script:
  - npm run build

after_success:
  - npm run tsdoc
  - bash build/deploy.sh

notifications:
  email:
    on_failure: always
