sudo: true
language: node_js
node_js:
  - "8"

branches:
  only:
    - /.*/

install:
  - yarn install --production=false
  - yarn test

script:
  - yarn build

after_success:
  - yarn tsdoc
  - bash build/deploy.sh

notifications:
  email:
    on_failure: always
